### PR TITLE
refactor: #15 Refactored ImportFromWkbPolygon to reduce complexity

### PR DESCRIPTION
**Pull request by gkrantz**

### CODE REVIEW

**Review by matteushast — APPROVED** [review]
Looks like a good refactor to me! But is the CC good enough?

**Comment by gkrantz** [comment]
Good catch Matteus
Sebastian said he will improve it further

**Comment by avocadomaster** [comment]
I have now improved it

**Review by matteushast — APPROVED** [review]
Nice! The refactor looks good and the CC is good!

**Pull request merged**
